# hd/k8s/product-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: teddysit722hd.azurecr.io/product_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          # Add health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            # Database connection details
            - name: POSTGRES_HOST
              value: product-db-service-hd
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-hd
                  key: PRODUCTS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-hd
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-hd
                  key: POSTGRES_PASSWORD
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-hd
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-hd
                  key: AZURE_STORAGE_ACCOUNT_KEY
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-hd
                  key: AZURE_STORAGE_CONTAINER_NAME
            - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-hd
                  key: AZURE_SAS_TOKEN_EXPIRY_HOURS
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000 # External port matching integration test expectations
      targetPort: 8000 # Container port
      name: http
  type: LoadBalancer
