# hd/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-hd
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for both Product DB and Order DB)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # Azure Storage Account Credentials for Product Service image uploads
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES from your Azure Storage Account

  AZURE_STORAGE_ACCOUNT_NAME: "c2l0NzIyZGV2b3BzdGVkZHlzdG9yYWdl"

  AZURE_STORAGE_ACCOUNT_KEY: "SDVMaHN6RzRQMEdTam44dVpkZ2k0UVFkRmcyNmtSY1d6ckNtMjVERlJCK0poUENSbWJWbk9DTmIzL2ZFSkFWY0tUZEczc1hkY2IwcCtBU3RhZVhoS0E9PQ=="
