name: Stage1 - CI Pipeline - Staging Branch

on:
  workflow_dispatch:
  push:
    branches: [staging]

jobs:
  # ---------------------------------------
  # 1️⃣ Test Backend Services
  # ---------------------------------------
  test-backend-services:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres -d postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        service: [order_service, product_service]

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Create databases if missing
        run: |
          for db in orders products; do
            psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/postgres \
              -tc "SELECT 1 FROM pg_database WHERE datname = '$db'" | grep -q 1 || \
              psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/postgres \
              -c "CREATE DATABASE $db;"
          done

      - name: Install dependencies
        run: |
          cd backend/${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Set DATABASE_URL
        run: |
          if [ "${{ matrix.service }}" = "order_service" ]; then
            echo "DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/orders" >> $GITHUB_ENV
          else
            echo "DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/products" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: |
          cd backend/${{ matrix.service }}
          python -m pytest tests/ -v

  # ---------------------------------------
  # 2️⃣ Build and Push Docker Images to ACR
  # ---------------------------------------
  build-and-push-docker-images:
    needs: test-backend-services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order_service, product_service, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login -u ${{ secrets.ACR_USERNAME }} --password-stdin ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Build Docker image
        run: |
          if [ "${{ matrix.service }}" = "frontend" ]; then
            cd frontend
          else
            cd backend/${{ matrix.service }}
          fi
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }}
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest

  # ---------------------------------------
  # 3️⃣ Scan Docker Images - Order Service
  # ---------------------------------------
  docker-scout-scan-order:
    needs: build-and-push-docker-images
    uses: ./.github/workflows/plugin-docker-scout-scan.yml
    with:
      IMAGE_NAME: order_service
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # ---------------------------------------
  # 3️⃣ Scan Docker Images - Product Service
  # ---------------------------------------
  docker-scout-scan-product:
    needs: build-and-push-docker-images
    uses: ./.github/workflows/plugin-docker-scout-scan.yml
    with:
      IMAGE_NAME: product_service
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # ---------------------------------------
  # 3️⃣ Scan Docker Images - Frontend
  # ---------------------------------------
  docker-scout-scan-frontend:
    needs: build-and-push-docker-images
    uses: ./.github/workflows/plugin-docker-scout-scan.yml
    with:
      IMAGE_NAME: frontend
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # ---------------------------------------
  # 4️⃣ Notify via Email on Failure
  # ---------------------------------------
  notify-email:
    needs:
      [
        docker-scout-scan-order,
        docker-scout-scan-product,
        docker-scout-scan-frontend,
      ]
    if: ${{ failure() }}
    uses: ./.github/workflows/plugin-send-email.yml
    with:
      email_to: "teddyhiny@gmail.com"
      email_subject: "CI Pipeline Failed on Staging Branch"
      email_body: |
        CI Pipeline for branch staging has failed.
        Commit: ${{ github.sha }}
        Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
