name: Stage2 - Staging Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Stage1 - CI Pipeline - Staging Branch"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.head_branch == 'staging' }}
    uses: ./.github/workflows/plugin-deploy.yml
    with:
      NAMESPACE: staging-${{ github.run_id }}
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
      STAGING: true

  create-pr:
    if: ${{ github.event.workflow_run.head_branch == 'staging' }}
    needs: deploy
    uses: ./.github/workflows/plugin-create-pull-request.yml
    with:
      SOURCE_BRANCH: staging
      TARGET_BRANCH: main
