name: Stage3 - Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/plugin-deploy.yml
    with:
      NAMESPACE: production
      IMAGE_TAG: latest
      STAGING: false
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
