name: Stage 3 - Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/plugin/deploy.yml
    with:
      NAMESPACE: production
      IMAGE_TAG: latest
      STAGING: false
