name: Manual IaC Teardown

on:
  workflow_dispatch: # manual trigger

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./infra
        run: terraform destroy -auto-approve
